; Using the substitution model, illustrate the process generated by each procedure in evaluating (+ 4 5). Are these processes iterative or recursive?

(define (+ a b)
  (if (= a 0)
      b
      (inc (+ (dec a) b))))

; This process is recursive because every iteration adds a delayed inc operation.
(+ 4 5)
(inc (+ 3 5))
(inc (inc (+ 2 5)))
(inc (inc (inc (+ 1 5))))
(inc (inc (inc (inc (+ 0 5)))))
(inc (inc (inc (inc 5))))
(inc (inc (inc 6)))
(inc (inc 7))
(inc 8)
9


(define (+ a b)
  (if (= a 0)
      b
      (+ (dec a) (inc b))))

; And this procedure is obviously iterative because no additional state is introduced on each step.
(+ 4 5)
(+ 3 6)
(+ 2 7)
(+ 1 8)
(+ 0 9)
9
